// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guoqzicdumkitkfocyiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1b3F6aWNkdW1raXRrZm9jeWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzg1OTMsImV4cCI6MjA2MTk1NDU5M30.gAYv3LabWa7r6nm3C_fZQ0XU8EYSssgX0OdUHqV4-SI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);